/*
 * Copyright 2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */


/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMX8MM6xxxKZ
package_id: MIMX8MM6CVTKZ
mcu_data: ksdk2_0
processor_version: 9.0.1
power_domains: {NVCC_NAND: '1.8'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: a53_0}
- pin_list:
  - {pin_num: B27, peripheral: XTALOSC, signal: xtalosc_xtal_in_24m, pin_signal: XTALI_24M}
  - {pin_num: P27, peripheral: uSDHC3, signal: usdhc_strobe, pin_signal: NAND_CE1_B}
  - {pin_num: M27, peripheral: uSDHC3, signal: 'usdhc_data, 5', pin_signal: NAND_CE2_B}
  - {pin_num: L27, peripheral: uSDHC3, signal: 'usdhc_data, 6', pin_signal: NAND_CE3_B}
  - {pin_num: K27, peripheral: uSDHC3, signal: 'usdhc_data, 7', pin_signal: NAND_CLE}
  - {pin_num: N27, peripheral: uSDHC3, signal: 'usdhc_data, 4', pin_signal: NAND_RE_B}
  - {pin_num: R26, peripheral: uSDHC3, signal: usdhc_clk, pin_signal: NAND_WE_B}
  - {pin_num: R27, peripheral: uSDHC3, signal: usdhc_cmd, pin_signal: NAND_WP_B}
  - {pin_num: M26, peripheral: uSDHC3, signal: 'usdhc_data, 0', pin_signal: NAND_DATA04}
  - {pin_num: L26, peripheral: uSDHC3, signal: 'usdhc_data, 1', pin_signal: NAND_DATA05}
  - {pin_num: K26, peripheral: uSDHC3, signal: 'usdhc_data, 2', pin_signal: NAND_DATA06}
  - {pin_num: N26, peripheral: uSDHC3, signal: 'usdhc_data, 3', pin_signal: NAND_DATA07}
  - {pin_num: W23, peripheral: uSDHC2, signal: usdhc_clk, pin_signal: SD2_CLK}
  - {pin_num: W24, peripheral: uSDHC2, signal: usdhc_cmd, pin_signal: SD2_CMD}
  - {pin_num: AB23, peripheral: uSDHC2, signal: 'usdhc_data, 0', pin_signal: SD2_DATA0}
  - {pin_num: AB24, peripheral: uSDHC2, signal: 'usdhc_data, 1', pin_signal: SD2_DATA1}
  - {pin_num: V24, peripheral: uSDHC2, signal: 'usdhc_data, 2', pin_signal: SD2_DATA2}
  - {pin_num: V23, peripheral: uSDHC2, signal: 'usdhc_data, 3', pin_signal: SD2_DATA3}
  - {pin_num: AA27, peripheral: uSDHC2, signal: usdhc_wp, pin_signal: SD2_WP}
  - {pin_num: AA26, peripheral: uSDHC2, signal: usdhc_cd_b, pin_signal: SD2_CD_B}
  - {pin_num: Y27, peripheral: uSDHC1, signal: 'usdhc_data, 0', pin_signal: SD1_DATA0}
  - {pin_num: V27, peripheral: uSDHC1, signal: usdhc_cmd, pin_signal: SD1_CMD}
  - {pin_num: Y26, peripheral: uSDHC1, signal: 'usdhc_data, 1', pin_signal: SD1_DATA1}
  - {pin_num: T26, peripheral: uSDHC1, signal: 'usdhc_data, 3', pin_signal: SD1_DATA3}
  - {pin_num: T27, peripheral: uSDHC1, signal: 'usdhc_data, 2', pin_signal: SD1_DATA2}
  - {pin_num: U27, peripheral: uSDHC1, signal: 'usdhc_data, 4', pin_signal: SD1_DATA4}
  - {pin_num: U26, peripheral: uSDHC1, signal: 'usdhc_data, 5', pin_signal: SD1_DATA5}
  - {pin_num: W27, peripheral: uSDHC1, signal: 'usdhc_data, 6', pin_signal: SD1_DATA6}
  - {pin_num: W26, peripheral: uSDHC1, signal: 'usdhc_data, 7', pin_signal: SD1_DATA7}
  - {pin_num: V26, peripheral: uSDHC1, signal: usdhc_clk, pin_signal: SD1_CLK}
  - {pin_num: AG11, peripheral: uSDHC1, signal: usdhc_cd_b, pin_signal: GPIO1_IO06}
  - {pin_num: AF11, peripheral: uSDHC1, signal: usdhc_wp, pin_signal: GPIO1_IO07}
  - {pin_num: F26, peripheral: CJTAG, signal: jtag_tck, pin_signal: JTAG_TCK}
  - {pin_num: E27, peripheral: CJTAG, signal: jtag_tdi, pin_signal: JTAG_TDI}
  - {pin_num: E26, peripheral: CJTAG, signal: jtag_tdo, pin_signal: JTAG_TDO}
  - {pin_num: F27, peripheral: CJTAG, signal: jtag_tms, pin_signal: JTAG_TMS}
  - {pin_num: C27, peripheral: CJTAG, signal: jtag_trst_b, pin_signal: JTAG_TRST_B}
  - {pin_num: E9, peripheral: I2C1, signal: i2c_scl, pin_signal: I2C1_SCL}
  - {pin_num: F9, peripheral: I2C1, signal: i2c_sda, pin_signal: I2C1_SDA}
  - {pin_num: D9, peripheral: I2C2, signal: i2c_sda, pin_signal: I2C2_SDA}
  - {pin_num: D10, peripheral: I2C2, signal: i2c_scl, pin_signal: I2C2_SCL}
  - {pin_num: F10, peripheral: I2C3, signal: i2c_sda, pin_signal: I2C3_SDA}
  - {pin_num: E10, peripheral: I2C3, signal: i2c_scl, pin_signal: I2C3_SCL}
  - {pin_num: AE27, peripheral: ENET1, signal: 'enet_rgmii_rd, 0', pin_signal: ENET_RD0}
  - {pin_num: AD27, peripheral: ENET1, signal: 'enet_rgmii_rd, 1', pin_signal: ENET_RD1}
  - {pin_num: AD26, peripheral: ENET1, signal: 'enet_rgmii_rd, 2', pin_signal: ENET_RD2}
  - {pin_num: AC26, peripheral: ENET1, signal: 'enet_rgmii_rd, 3', pin_signal: ENET_RD3}
  - {pin_num: AF26, peripheral: ENET1, signal: 'enet_rgmii_td, 1', pin_signal: ENET_TD1}
  - {pin_num: AG25, peripheral: ENET1, signal: 'enet_rgmii_td, 2', pin_signal: ENET_TD2}
  - {pin_num: AF25, peripheral: ENET1, signal: 'enet_rgmii_td, 3', pin_signal: ENET_TD3}
  - {pin_num: AG26, peripheral: ENET1, signal: 'enet_rgmii_td, 0', pin_signal: ENET_TD0}
  - {pin_num: AG24, peripheral: ENET1, signal: enet_rgmii_txc, pin_signal: ENET_TXC}
  - {pin_num: AF24, peripheral: ENET1, signal: enet_rgmii_tx_ctl, pin_signal: ENET_TX_CTL}
  - {pin_num: AF27, peripheral: ENET1, signal: enet_rgmii_rx_ctl, pin_signal: ENET_RX_CTL}
  - {pin_num: AE26, peripheral: ENET1, signal: enet_rgmii_rxc, pin_signal: ENET_RXC}
  - {pin_num: AC27, peripheral: ENET1, signal: enet_mdc, pin_signal: ENET_MDC}
  - {pin_num: AB27, peripheral: ENET1, signal: enet_mdio, pin_signal: ENET_MDIO}
  - {pin_num: A22, peripheral: USB1, signal: usb_dn, pin_signal: USB1_DN}
  - {pin_num: B22, peripheral: USB1, signal: usb_dp, pin_signal: USB1_DP}
  - {pin_num: B23, peripheral: USB2, signal: usb_dp, pin_signal: USB2_DP}
  - {pin_num: A23, peripheral: USB2, signal: usb_dn, pin_signal: USB2_DN}
  - {pin_num: D23, peripheral: USB2, signal: usb_id, pin_signal: USB2_ID}
  - {pin_num: AD9, peripheral: USB1, signal: usb_otg_oc, pin_signal: GPIO1_IO13}
  - {pin_num: AB10, peripheral: USB1, signal: usb_otg_pwr, pin_signal: GPIO1_IO12}
  - {pin_num: F22, peripheral: USB1, signal: usb_vbus, pin_signal: USB1_VBUS}
  - {pin_num: D22, peripheral: USB1, signal: usb_id, pin_signal: USB1_ID}
  - {pin_num: F23, peripheral: USB2, signal: usb_vbus, pin_signal: USB2_VBUS}
  - {pin_num: AC9, peripheral: USB2, signal: usb_otg_pwr, pin_signal: GPIO1_IO14}
  - {pin_num: AB9, peripheral: USB2, signal: usb_otg_oc, pin_signal: GPIO1_IO15}
  - {pin_num: A7, peripheral: ECSPI1, signal: ecspi_miso, pin_signal: ECSPI1_MISO}
  - {pin_num: B7, peripheral: ECSPI1, signal: ecspi_mosi, pin_signal: ECSPI1_MOSI}
  - {pin_num: D6, peripheral: ECSPI1, signal: ecspi_sclk, pin_signal: ECSPI1_SCLK}
  - {pin_num: B6, peripheral: ECSPI1, signal: 'ecspi_ss, 0', pin_signal: ECSPI1_SS0}
  - {pin_num: N22, peripheral: QSPI, signal: qspi_a_sclk, pin_signal: NAND_ALE}
  - {pin_num: N24, peripheral: QSPI, signal: qspi_a_ss0_b, pin_signal: NAND_CE0_B}
  - {pin_num: P23, peripheral: QSPI, signal: 'qspi_a_data, 0', pin_signal: NAND_DATA00}
  - {pin_num: K24, peripheral: QSPI, signal: 'qspi_a_data, 1', pin_signal: NAND_DATA01}
  - {pin_num: K23, peripheral: QSPI, signal: 'qspi_a_data, 2', pin_signal: NAND_DATA02}
  - {pin_num: N23, peripheral: QSPI, signal: 'qspi_a_data, 3', pin_signal: NAND_DATA03}
  - {pin_num: A16, peripheral: MIPI_CSI, signal: mipi_csi_clk_n, pin_signal: MIPI_CSI_CLK_N}
  - {pin_num: B16, peripheral: MIPI_CSI, signal: mipi_csi_clk_p, pin_signal: MIPI_CSI_CLK_P}
  - {pin_num: A14, peripheral: MIPI_CSI, signal: mipi_csi_d0_n, pin_signal: MIPI_CSI_D0_N}
  - {pin_num: B14, peripheral: MIPI_CSI, signal: mipi_csi_d0_p, pin_signal: MIPI_CSI_D0_P}
  - {pin_num: A15, peripheral: MIPI_CSI, signal: mipi_csi_d1_n, pin_signal: MIPI_CSI_D1_N}
  - {pin_num: B15, peripheral: MIPI_CSI, signal: mipi_csi_d1_p, pin_signal: MIPI_CSI_D1_P}
  - {pin_num: A17, peripheral: MIPI_CSI, signal: mipi_csi_d2_n, pin_signal: MIPI_CSI_D2_N}
  - {pin_num: B17, peripheral: MIPI_CSI, signal: mipi_csi_d2_p, pin_signal: MIPI_CSI_D2_P}
  - {pin_num: A18, peripheral: MIPI_CSI, signal: mipi_csi_d3_n, pin_signal: MIPI_CSI_D3_N}
  - {pin_num: B18, peripheral: MIPI_CSI, signal: mipi_csi_d3_p, pin_signal: MIPI_CSI_D3_P}
  - {pin_num: A11, peripheral: MIPI_DSI, signal: mipi_dsi_clk_n, pin_signal: MIPI_DSI_CLK_N}
  - {pin_num: B11, peripheral: MIPI_DSI, signal: mipi_dsi_clk_p, pin_signal: MIPI_DSI_CLK_P}
  - {pin_num: A9, peripheral: MIPI_DSI, signal: mipi_dsi_d0_n, pin_signal: MIPI_DSI_D0_N}
  - {pin_num: B9, peripheral: MIPI_DSI, signal: mipi_dsi_d0_p, pin_signal: MIPI_DSI_D0_P}
  - {pin_num: A10, peripheral: MIPI_DSI, signal: mipi_dsi_d1_n, pin_signal: MIPI_DSI_D1_N}
  - {pin_num: B10, peripheral: MIPI_DSI, signal: mipi_dsi_d1_p, pin_signal: MIPI_DSI_D1_P}
  - {pin_num: A12, peripheral: MIPI_DSI, signal: mipi_dsi_d2_n, pin_signal: MIPI_DSI_D2_N}
  - {pin_num: B12, peripheral: MIPI_DSI, signal: mipi_dsi_d2_p, pin_signal: MIPI_DSI_D2_P}
  - {pin_num: A13, peripheral: MIPI_DSI, signal: mipi_dsi_d3_n, pin_signal: MIPI_DSI_D3_N}
  - {pin_num: B13, peripheral: MIPI_DSI, signal: mipi_dsi_d3_p, pin_signal: MIPI_DSI_D3_P}
  - {pin_num: D15, peripheral: MIPI_DSI, signal: mipi_dsi_rext, pin_signal: MIPI_DSI_REXT}
  - {pin_num: A19, peripheral: PCIE1, signal: pcie_rxn_n, pin_signal: PCIE_RXN_N}
  - {pin_num: B19, peripheral: PCIE1, signal: pcie_rxn_p, pin_signal: PCIE_RXN_P}
  - {pin_num: A20, peripheral: PCIE1, signal: pcie_txn_n, pin_signal: PCIE_TXN_N}
  - {pin_num: B20, peripheral: PCIE1, signal: pcie_txn_p, pin_signal: PCIE_TXN_P}
  - {pin_num: A21, peripheral: PCIE1, signal: pcie_ref_pad_clk_n, pin_signal: PCIE_REF_PAD_CLK_N}
  - {pin_num: B21, peripheral: PCIE1, signal: pcie_ref_pad_clk_p, pin_signal: PCIE_REF_PAD_CLK_P}
  - {pin_num: E14, peripheral: UART1, signal: uart_rx, pin_signal: UART1_RXD}
  - {pin_num: F13, peripheral: UART1, signal: uart_tx, pin_signal: UART1_TXD}
  - {pin_num: F15, peripheral: UART2, signal: uart_rx, pin_signal: UART2_RXD}
  - {pin_num: E15, peripheral: UART2, signal: uart_tx, pin_signal: UART2_TXD}
  - {pin_num: D18, peripheral: UART3, signal: uart_tx, pin_signal: UART3_TXD}
  - {pin_num: E18, peripheral: UART3, signal: uart_rx, pin_signal: UART3_RXD}
  - {pin_num: AC24, peripheral: UART1, signal: uart_cts_b, pin_signal: SAI2_RXD0}
  - {pin_num: AD23, peripheral: UART1, signal: uart_rts_b, pin_signal: SAI2_TXFS}
  - {pin_num: F19, peripheral: UART2, signal: uart_cts_b, pin_signal: UART4_RXD}
  - {pin_num: F18, peripheral: UART2, signal: uart_rts_b, pin_signal: UART4_TXD}
  - {pin_num: AF14, peripheral: PWM1, signal: pwm_out, pin_signal: GPIO1_IO01}
  - {pin_num: D13, peripheral: PWM2, signal: pwm_out, pin_signal: I2C4_SCL}
  - {pin_num: AF9, peripheral: PWM3, signal: pwm_out, pin_signal: SPDIF_TX}
  - {pin_num: A4, peripheral: DRAM, signal: 'dram_dm, 0', pin_signal: DRAM_DM0}
  - {pin_num: F1, peripheral: DRAM, signal: 'dram_dm, 1', pin_signal: DRAM_DM1}
  - {pin_num: AB1, peripheral: DRAM, signal: 'dram_dm, 2', pin_signal: DRAM_DM2}
  - {pin_num: AG4, peripheral: DRAM, signal: 'dram_dm, 3', pin_signal: DRAM_DM3}
  - {pin_num: A5, peripheral: DRAM, signal: 'dram_dq, 00', pin_signal: DRAM_DQ00}
  - {pin_num: B5, peripheral: DRAM, signal: 'dram_dq, 01', pin_signal: DRAM_DQ01}
  - {pin_num: D2, peripheral: DRAM, signal: 'dram_dq, 02', pin_signal: DRAM_DQ02}
  - {pin_num: D1, peripheral: DRAM, signal: 'dram_dq, 03', pin_signal: DRAM_DQ03}
  - {pin_num: C1, peripheral: DRAM, signal: 'dram_dq, 04', pin_signal: DRAM_DQ04}
  - {pin_num: B1, peripheral: DRAM, signal: 'dram_dq, 05', pin_signal: DRAM_DQ05}
  - {pin_num: A3, peripheral: DRAM, signal: 'dram_dq, 06', pin_signal: DRAM_DQ06}
  - {pin_num: B4, peripheral: DRAM, signal: 'dram_dq, 07', pin_signal: DRAM_DQ07}
  - {pin_num: F2, peripheral: DRAM, signal: 'dram_dq, 08', pin_signal: DRAM_DQ08}
  - {pin_num: G2, peripheral: DRAM, signal: 'dram_dq, 09', pin_signal: DRAM_DQ09}
  - {pin_num: J1, peripheral: DRAM, signal: 'dram_dq, 10', pin_signal: DRAM_DQ10}
  - {pin_num: J2, peripheral: DRAM, signal: 'dram_dq, 11', pin_signal: DRAM_DQ11}
  - {pin_num: K2, peripheral: DRAM, signal: 'dram_dq, 12', pin_signal: DRAM_DQ12}
  - {pin_num: K1, peripheral: DRAM, signal: 'dram_dq, 13', pin_signal: DRAM_DQ13}
  - {pin_num: E1, peripheral: DRAM, signal: 'dram_dq, 14', pin_signal: DRAM_DQ14}
  - {pin_num: E2, peripheral: DRAM, signal: 'dram_dq, 15', pin_signal: DRAM_DQ15}
  - {pin_num: AB2, peripheral: DRAM, signal: 'dram_dq, 16', pin_signal: DRAM_DQ16}
  - {pin_num: AA2, peripheral: DRAM, signal: 'dram_dq, 17', pin_signal: DRAM_DQ17}
  - {pin_num: W1, peripheral: DRAM, signal: 'dram_dq, 18', pin_signal: DRAM_DQ18}
  - {pin_num: W2, peripheral: DRAM, signal: 'dram_dq, 19', pin_signal: DRAM_DQ19}
  - {pin_num: V2, peripheral: DRAM, signal: 'dram_dq, 20', pin_signal: DRAM_DQ20}
  - {pin_num: V1, peripheral: DRAM, signal: 'dram_dq, 21', pin_signal: DRAM_DQ21}
  - {pin_num: AC2, peripheral: DRAM, signal: 'dram_dq, 23', pin_signal: DRAM_DQ23}
  - {pin_num: AC1, peripheral: DRAM, signal: 'dram_dq, 22', pin_signal: DRAM_DQ22}
  - {pin_num: AG5, peripheral: DRAM, signal: 'dram_dq, 24', pin_signal: DRAM_DQ24}
  - {pin_num: AF5, peripheral: DRAM, signal: 'dram_dq, 25', pin_signal: DRAM_DQ25}
  - {pin_num: AD2, peripheral: DRAM, signal: 'dram_dq, 26', pin_signal: DRAM_DQ26}
  - {pin_num: AD1, peripheral: DRAM, signal: 'dram_dq, 27', pin_signal: DRAM_DQ27}
  - {pin_num: AE1, peripheral: DRAM, signal: 'dram_dq, 28', pin_signal: DRAM_DQ28}
  - {pin_num: AF1, peripheral: DRAM, signal: 'dram_dq, 29', pin_signal: DRAM_DQ29}
  - {pin_num: AG3, peripheral: DRAM, signal: 'dram_dq, 30', pin_signal: DRAM_DQ30}
  - {pin_num: AF4, peripheral: DRAM, signal: 'dram_dq, 31', pin_signal: DRAM_DQ31}
  - {pin_num: AG2, peripheral: DRAM, signal: dram_dqs3_p, pin_signal: DRAM_DQS3_P}
  - {pin_num: AF2, peripheral: DRAM, signal: dram_dqs3_n, pin_signal: DRAM_DQS3_N}
  - {pin_num: AA1, peripheral: DRAM, signal: dram_dqs2_p, pin_signal: DRAM_DQS2_P}
  - {pin_num: G1, peripheral: DRAM, signal: dram_dqs1_p, pin_signal: DRAM_DQS1_P}
  - {pin_num: B2, peripheral: DRAM, signal: dram_dqs0_n, pin_signal: DRAM_DQS0_N}
  - {pin_num: A2, peripheral: DRAM, signal: dram_dqs0_p, pin_signal: DRAM_DQS0_P}
  - {pin_num: H1, peripheral: DRAM, signal: dram_dqs1_n, pin_signal: DRAM_DQS1_N}
  - {pin_num: Y1, peripheral: DRAM, signal: dram_dqs2_n, pin_signal: DRAM_DQS2_N}
  - {pin_num: R1, peripheral: DRAM, signal: dram_reset_n, pin_signal: DRAM_RESET_N}
  - {pin_num: P1, peripheral: DRAM, signal: dram_vref, pin_signal: DRAM_VREF}
  - {pin_num: P2, peripheral: DRAM, signal: dram_zn, pin_signal: DRAM_ZN}
  - {pin_num: R2, peripheral: DRAM, signal: dram_alert_n, pin_signal: DRAM_ALERT_N}
  - {pin_num: F4, peripheral: DRAM, signal: 'dram_ac, 00', pin_signal: DRAM_AC00}
  - {pin_num: F5, peripheral: DRAM, signal: 'dram_ac, 01', pin_signal: DRAM_AC01}
  - {pin_num: K4, peripheral: DRAM, signal: 'dram_ac, 02', pin_signal: DRAM_AC02}
  - {pin_num: J4, peripheral: DRAM, signal: 'dram_ac, 03', pin_signal: DRAM_AC03}
  - {pin_num: L2, peripheral: DRAM, signal: 'dram_ac, 04', pin_signal: DRAM_AC04}
  - {pin_num: L1, peripheral: DRAM, signal: 'dram_ac, 05', pin_signal: DRAM_AC05}
  - {pin_num: J6, peripheral: DRAM, signal: 'dram_ac, 08', pin_signal: DRAM_AC08}
  - {pin_num: K6, peripheral: DRAM, signal: 'dram_ac, 09', pin_signal: DRAM_AC09}
  - {pin_num: E4, peripheral: DRAM, signal: 'dram_ac, 10', pin_signal: DRAM_AC10}
  - {pin_num: D5, peripheral: DRAM, signal: 'dram_ac, 11', pin_signal: DRAM_AC11}
  - {pin_num: N4, peripheral: DRAM, signal: 'dram_ac, 12', pin_signal: DRAM_AC12}
  - {pin_num: N5, peripheral: DRAM, signal: 'dram_ac, 13', pin_signal: DRAM_AC13}
  - {pin_num: AB4, peripheral: DRAM, signal: 'dram_ac, 20', pin_signal: DRAM_AC20}
  - {pin_num: AB5, peripheral: DRAM, signal: 'dram_ac, 21', pin_signal: DRAM_AC21}
  - {pin_num: W4, peripheral: DRAM, signal: 'dram_ac, 22', pin_signal: DRAM_AC22}
  - {pin_num: V4, peripheral: DRAM, signal: 'dram_ac, 23', pin_signal: DRAM_AC23}
  - {pin_num: U2, peripheral: DRAM, signal: 'dram_ac, 24', pin_signal: DRAM_AC24}
  - {pin_num: U1, peripheral: DRAM, signal: 'dram_ac, 25', pin_signal: DRAM_AC25}
  - {pin_num: W6, peripheral: DRAM, signal: 'dram_ac, 28', pin_signal: DRAM_AC28}
  - {pin_num: V6, peripheral: DRAM, signal: 'dram_ac, 29', pin_signal: DRAM_AC29}
  - {pin_num: AC4, peripheral: DRAM, signal: 'dram_ac, 30', pin_signal: DRAM_AC30}
  - {pin_num: AD5, peripheral: DRAM, signal: 'dram_ac, 31', pin_signal: DRAM_AC31}
  - {pin_num: R4, peripheral: DRAM, signal: 'dram_ac, 32', pin_signal: DRAM_AC32}
  - {pin_num: R5, peripheral: DRAM, signal: 'dram_ac, 33', pin_signal: DRAM_AC33}
  - {pin_num: AF19, peripheral: SAI6, signal: sai_mclk, pin_signal: SAI1_RXD7}
  - {pin_num: AF18, peripheral: SAI6, signal: 'sai_rx_data, 0', pin_signal: SAI1_RXD5}
  - {pin_num: AG22, peripheral: SAI6, signal: sai_tx_bclk, pin_signal: SAI1_TXD4}
  - {pin_num: AF22, peripheral: SAI6, signal: 'sai_tx_data, 0', pin_signal: SAI1_TXD5}
  - {pin_num: AG23, peripheral: SAI6, signal: sai_tx_sync, pin_signal: SAI1_TXD6}
  - {pin_num: E6, peripheral: UART4, signal: uart_rx, pin_signal: ECSPI2_SCLK}
  - {pin_num: B8, peripheral: UART4, signal: uart_tx, pin_signal: ECSPI2_MOSI}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MISO_ECSPI1_MISO, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MOSI_ECSPI1_MOSI, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SCLK_ECSPI1_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SS0_ECSPI1_SS0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_MOSI_UART4_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_SCLK_UART4_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_MDC_ENET1_MDC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_MDIO_ENET1_MDIO, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD0_ENET1_RGMII_RD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD1_ENET1_RGMII_RD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD2_ENET1_RGMII_RD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD3_ENET1_RGMII_RD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RXC_ENET1_RGMII_RXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RX_CTL_ENET1_RGMII_RX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD0_ENET1_RGMII_TD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD1_ENET1_RGMII_TD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD2_ENET1_RGMII_TD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD3_ENET1_RGMII_TD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TXC_ENET1_RGMII_TXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TX_CTL_ENET1_RGMII_TX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO01_PWM1_OUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO06_USDHC1_CD_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO07_USDHC1_WP, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO12_USB1_OTG_PWR, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO13_USB1_OTG_OC, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO14_USB2_OTG_PWR, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO15_USB2_OTG_OC, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C1_SCL_I2C1_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C1_SDA_I2C1_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C2_SCL_I2C2_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C2_SDA_I2C2_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_I2C3_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_I2C3_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C4_SCL_PWM2_OUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_ALE_QSPI_A_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE0_B_QSPI_A_SS0_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE1_B_USDHC3_STROBE, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE2_B_USDHC3_DATA5, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE3_B_USDHC3_DATA6, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CLE_USDHC3_DATA7, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA00_QSPI_A_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA01_QSPI_A_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA02_QSPI_A_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA03_QSPI_A_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA04_USDHC3_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA05_USDHC3_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA06_USDHC3_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA07_USDHC3_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_RE_B_USDHC3_DATA4, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WE_B_USDHC3_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WP_B_USDHC3_CMD, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD5_SAI6_RX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD7_SAI6_MCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD4_SAI6_TX_BCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD5_SAI6_TX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD6_SAI6_TX_SYNC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXD0_UART1_CTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI2_TXFS_UART1_RTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CLK_USDHC1_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CMD_USDHC1_CMD, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA0_USDHC1_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA1_USDHC1_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA2_USDHC1_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA3_USDHC1_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA4_USDHC1_DATA4, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA5_USDHC1_DATA5, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA6_USDHC1_DATA6, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA7_USDHC1_DATA7, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_CD_B_USDHC2_CD_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_CLK_USDHC2_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_CMD_USDHC2_CMD, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA0_USDHC2_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA1_USDHC2_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA2_USDHC2_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA3_USDHC2_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_WP_USDHC2_WP, 0U);
    IOMUXC_SetPinMux(IOMUXC_SPDIF_TX_PWM3_OUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_RXD_UART1_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_TXD_UART1_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_RXD_UART2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_TXD_UART2_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_RXD_UART3_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_TXD_UART3_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_RXD_UART2_CTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_TXD_UART2_RTS_B, 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
